"""HTML and Slack templates for daily report rendering."""

from typing import Any

# ---------------------------------------------------------------------------
# HTML Report Template
# ---------------------------------------------------------------------------

HTML_REPORT_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Macro Trading Daily Report - {report_date}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         max-width: 800px; margin: 0 auto; padding: 20px; background: #f5f5f5; color: #333; }}
  .header {{ background: #1a1a2e; color: #fff; padding: 24px; border-radius: 8px 8px 0 0; }}
  .header h1 {{ margin: 0; font-size: 22px; }}
  .header .date {{ color: #aaa; font-size: 14px; margin-top: 4px; }}
  .section {{ background: #fff; border: 1px solid #e0e0e0; padding: 20px; margin-bottom: 2px; }}
  .section h2 {{ font-size: 16px; color: #1a1a2e; margin: 0 0 12px 0;
    border-bottom: 2px solid #e8e8e8; padding-bottom: 8px; }}
  .section:last-child {{ border-radius: 0 0 8px 8px; margin-bottom: 20px; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  th {{ background: #f0f0f0; text-align: left; padding: 8px 10px; font-weight: 600; }}
  td {{ padding: 8px 10px; border-bottom: 1px solid #eee; }}
  .positive {{ color: #16a34a; font-weight: 600; }}
  .negative {{ color: #dc2626; font-weight: 600; }}
  .warning {{ color: #d97706; font-weight: 600; }}
  .neutral {{ color: #6b7280; }}
  .badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }}
  .badge-green {{ background: #dcfce7; color: #16a34a; }}
  .badge-red {{ background: #fee2e2; color: #dc2626; }}
  .badge-yellow {{ background: #fef3c7; color: #d97706; }}
  .badge-blue {{ background: #dbeafe; color: #2563eb; }}
  .commentary {{ font-size: 13px; color: #555; margin-top: 10px; font-style: italic; }}
  .chart-container {{ text-align: center; margin: 12px 0; }}
  .chart-container img {{ max-width: 100%; border-radius: 4px; }}
  .footer {{ text-align: center; color: #999; font-size: 12px; padding: 16px; }}
  .action-item {{ background: #f8fafc; border-left: 3px solid #2563eb;
    padding: 10px 14px; margin: 8px 0; border-radius: 0 4px 4px 0; }}
  .action-item.high {{ border-left-color: #dc2626; }}
  .action-item.medium {{ border-left-color: #d97706; }}
</style>
</head>
<body>
<div class="header">
  <h1>Macro Trading Daily Report</h1>
  <div class="date">{report_date} | Generated at {generation_timestamp}</div>
</div>
{sections_html}
<div class="footer">Generated by Macro Trading System | {report_date}</div>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Slack Summary Template (Block Kit)
# ---------------------------------------------------------------------------

SLACK_SUMMARY_TEMPLATE = {
    "blocks": [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": "Macro Trading Daily Report - {report_date}",
            },
        },
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": "*Portfolio Return:*\n{portfolio_return}"},
                {"type": "mrkdwn", "text": "*VaR 95%:*\n{var_95}"},
            ],
        },
        {"type": "divider"},
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": "*Regime:*\n{regime}"},
                {"type": "mrkdwn", "text": "*Risk Status:*\n{risk_status}"},
            ],
        },
        {"type": "divider"},
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": "*Top Signals:*\n{top_signals}"},
        },
        {"type": "divider"},
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": ":chart_with_upwards_trend: {action_count} action items"
                    " | <{report_url}|View Full Report>",
                },
            ],
        },
    ],
}


# ---------------------------------------------------------------------------
# Rendering Functions
# ---------------------------------------------------------------------------


def render_html(sections: dict, charts: dict[str, str] | None = None) -> str:
    """Fill the HTML template with section data and optional base64 chart images."""
    from datetime import datetime

    charts = charts or {}
    sections_html_parts: list[str] = []

    for section_key, section in sections.items():
        title = section.title
        content = section.content
        commentary = section.commentary

        part = f'<div class="section"><h2>{title}</h2>\n'

        # Render content as table if it has tabular data
        if isinstance(content, dict) and content:
            if any(isinstance(v, list) for v in content.values()):
                part += _render_list_table(content)
            else:
                part += _render_kv_table(content)

        # Embed chart if available
        if section_key in charts:
            part += (
                f'<div class="chart-container">'
                f'<img src="data:image/png;base64,{charts[section_key]}"'
                f' alt="{title} chart"/></div>\n'
            )

        if commentary:
            part += f'<div class="commentary">{commentary}</div>\n'
        part += "</div>\n"
        sections_html_parts.append(part)

    return HTML_REPORT_TEMPLATE.format(
        report_date=sections.get(
            "market_snapshot", next(iter(sections.values()))
        ).content.get("date", "N/A"),
        generation_timestamp=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        sections_html="\n".join(sections_html_parts),
    )


def render_slack_blocks(summary: dict) -> list[dict]:
    """Generate Slack Block Kit blocks from summary data."""
    import copy
    import json

    template = copy.deepcopy(SLACK_SUMMARY_TEMPLATE)
    raw = json.dumps(template["blocks"])

    replacements = {
        "{report_date}": str(summary.get("report_date", "N/A")),
        "{portfolio_return}": summary.get("portfolio_return", "N/A"),
        "{var_95}": summary.get("var_95", "N/A"),
        "{regime}": summary.get("regime", "N/A"),
        "{risk_status}": summary.get("risk_status", "N/A"),
        "{top_signals}": summary.get("top_signals", "N/A"),
        "{action_count}": str(summary.get("action_count", 0)),
        "{report_url}": summary.get("report_url", "#"),
    }
    for placeholder, value in replacements.items():
        raw = raw.replace(placeholder, value)

    return json.loads(raw)


def render_markdown(sections: dict) -> str:
    """Generate a markdown report with tables and headers."""
    lines: list[str] = []
    lines.append("# Macro Trading Daily Report\n")

    for _key, section in sections.items():
        lines.append(f"## {section.title}\n")

        content = section.content
        if isinstance(content, dict):
            if any(isinstance(v, list) for v in content.values()):
                lines.append(_render_md_list_table(content))
            else:
                for k, v in content.items():
                    lines.append(f"- **{k}**: {v}")
                lines.append("")

        if section.commentary:
            lines.append(f"*{section.commentary}*\n")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _render_kv_table(data: dict) -> str:
    """Render a key-value dict as a 2-column HTML table."""
    rows = "".join(
        f"<tr><td><b>{k}</b></td><td>{_format_value(v)}</td></tr>\n"
        for k, v in data.items()
    )
    return f"<table><tbody>\n{rows}</tbody></table>\n"


def _render_list_table(data: dict) -> str:
    """Render a dict of parallel lists as an HTML table."""
    keys = list(data.keys())
    first_list = next((v for v in data.values() if isinstance(v, list)), [])
    n_rows = len(first_list)

    header = "".join(f"<th>{k}</th>" for k in keys)
    rows = ""
    for i in range(n_rows):
        cells = ""
        for k in keys:
            v = data[k]
            cell_val = v[i] if isinstance(v, list) and i < len(v) else v
            cells += f"<td>{_format_value(cell_val)}</td>"
        rows += f"<tr>{cells}</tr>\n"

    return f"<table><thead><tr>{header}</tr></thead><tbody>\n{rows}</tbody></table>\n"


def _render_md_list_table(data: dict) -> str:
    """Render a dict of parallel lists as a markdown table."""
    keys = list(data.keys())
    first_list = next((v for v in data.values() if isinstance(v, list)), [])
    n_rows = len(first_list)

    header = "| " + " | ".join(keys) + " |"
    separator = "| " + " | ".join("---" for _ in keys) + " |"
    rows = ""
    for i in range(n_rows):
        cells = []
        for k in keys:
            v = data[k]
            cell_val = v[i] if isinstance(v, list) and i < len(v) else v
            cells.append(str(cell_val))
        rows += "| " + " | ".join(cells) + " |\n"

    return f"{header}\n{separator}\n{rows}"


def _format_value(v: Any) -> str:
    """Format a value for HTML display with color coding."""
    if isinstance(v, float):
        if v > 0:
            return f'<span class="positive">+{v:.4f}</span>'
        elif v < 0:
            return f'<span class="negative">{v:.4f}</span>'
        return f'<span class="neutral">{v:.4f}</span>'
    return str(v)
